import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import type { Category, Client, Product, ProductClientCode, ProductUnit } from '../api/types';
import * as api from '../api/client';
import { useI18n } from '../i18n/I18nContext';

const wasteSuggestions = ['15 01 01','15 01 02','20 01 01'];
const blank: Omit<Product,'id'|'accountId'|'createdAt'> = { code:'', folder:'', unit:'pcs', showInPriceList:false, name:{et:'',ru:'',en:''}, description:{et:'',ru:'',en:''}, clientCodes:[], wasteCodes:[] };

type FormData = Omit<Product,'id'|'accountId'|'createdAt'>;
export function ProductFormPage() {
 const { id } = useParams(); const edit=Boolean(id); const navigate=useNavigate(); const { t }=useI18n();
 const [form,setForm]=useState<FormData>(blank); const [cats,setCats]=useState<Category[]>([]); const [clients,setClients]=useState<Client[]>([]); const [errors,setErrors]=useState<Record<string,string>>({}); const [waste,setWaste]=useState('');
 useEffect(()=>{ api.listCategories().then(setCats); api.listClients({pageSize:100}).then(r=>setClients(r.data)); if(id) api.getProduct(id).then(p=>setForm(p)); },[id]);
 function set<K extends keyof FormData>(key:K,value:FormData[K]){setForm(p=>({...p,[key]:value}));}
 function validate(){const e:Record<string,string>={}; if(!form.code)e.code='Required'; if(form.code.length>20)e.code='Max 20 chars'; if(!form.folder)e.folder='Required'; if(form.folder.length>3)e.folder='Max 3 chars'; if((form.ean?.length??0)>13)e.ean='Max 13 chars'; if(form.sortOrder && String(form.sortOrder).length>6)e.sortOrder='Max 6 digits'; setErrors(e); return Object.keys(e).length===0;}
 async function submit(e:FormEvent){e.preventDefault(); if(!validate())return; edit&&id?await api.updateProduct(id,form):await api.createProduct(form); navigate('/products');}
 function updateClientCode(i:number, patch:Partial<ProductClientCode>){set('clientCodes',form.clientCodes.map((r,idx)=>idx===i?{...r,...patch}:r));}
 function addWaste(){const v=waste.trim(); if(v && !form.wasteCodes.includes(v)) set('wasteCodes',[...form.wasteCodes,v]); setWaste('');}
 return <form onSubmit={submit}><div className="page-header"><h1>{edit?'Edit product':'New product'}</h1><div><Link className="ghost button" to="/products">{t('cancel')}</Link><button>{t('save')}</button></div></div>
 <section className="card form-grid"><Field label="Код" error={errors.code}><input maxLength={20} value={form.code} onChange={e=>set('code',e.target.value)}/></Field><Field label="Папка" error={errors.folder}><select value={form.folder} onChange={e=>set('folder',e.target.value)}><option value="">---</option>{cats.map(c=><option key={c.code} value={c.code}>{c.code} — {c.name.en}</option>)}</select></Field><Field label="EAN" error={errors.ean}><input maxLength={13} value={form.ean??''} onChange={e=>set('ean',e.target.value)}/></Field><Field label="Порядок" error={errors.sortOrder}><input type="number" value={form.sortOrder??''} onChange={e=>set('sortOrder',e.target.value?Number(e.target.value):undefined)}/></Field><label>Ед.<select value={form.unit} onChange={e=>set('unit',e.target.value as ProductUnit)}><option value="ton">тонна</option><option value="kg">кг</option><option value="pcs">шт</option><option value="hour">час</option><option value="km">км</option><option value="day">день</option></select></label><label className="checkbox"><input type="checkbox" checked={form.showInPriceList} onChange={e=>set('showInPriceList',e.target.checked)}/>Показывать в прайсе</label></section>
 <h2>Наименование</h2><section className="card form-grid"><label>ET<input value={form.name.et} onChange={e=>set('name',{...form.name,et:e.target.value})}/></label><label>RU<input value={form.name.ru} onChange={e=>set('name',{...form.name,ru:e.target.value})}/></label><label>EN<input value={form.name.en} onChange={e=>set('name',{...form.name,en:e.target.value})}/></label></section>
 <h2>Описание</h2><section className="card form-grid"><label>ET<textarea value={form.description.et} onChange={e=>set('description',{...form.description,et:e.target.value})}/></label><label>RU<textarea value={form.description.ru} onChange={e=>set('description',{...form.description,ru:e.target.value})}/></label><label>EN<textarea value={form.description.en} onChange={e=>set('description',{...form.description,en:e.target.value})}/></label></section>
 <h2>Код клиента</h2><section className="card"><div className="stack">{form.clientCodes.map((row,i)=><div className="inline-row" key={i}><select value={row.clientId} onChange={e=>updateClientCode(i,{clientId:e.target.value})}><option value="">Client</option>{clients.map(c=><option key={c.id} value={c.id}>{c.type==='private'?`${c.firstName} ${c.lastName}`:c.companyName}</option>)}</select><input placeholder="Code" value={row.code} onChange={e=>updateClientCode(i,{code:e.target.value})}/><button type="button" className="ghost" onClick={()=>set('clientCodes',form.clientCodes.filter((_,idx)=>idx!==i))}>Remove</button></div>)}<button type="button" className="secondary" onClick={()=>set('clientCodes',[...form.clientCodes,{clientId:'',code:''}])}>Add row</button></div></section>
 <h2>Код отходов</h2><section className="card"><div className="inline-row"><input list="waste" value={waste} onChange={e=>setWaste(e.target.value)} placeholder="15 01 01"/><datalist id="waste">{wasteSuggestions.map(x=><option key={x} value={x}/>)}</datalist><button type="button" onClick={addWaste}>Add</button></div><div className="tags">{form.wasteCodes.map(x=><span className="tag" key={x}>{x}<button type="button" onClick={()=>set('wasteCodes',form.wasteCodes.filter(w=>w!==x))}>×</button></span>)}</div></section>
 </form>;
}
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label>{label}{children}{error && <span className="field-error">{error}</span>}</label>; }
