FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o migrations ./cmd

FROM alpine:latest

COPY --from=builder /app/migrations /migrations

CMD ["/migrations"]